apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
  namespace: chatapp
type: Opaque
data:
  jwt: "ZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjME16UTBNREkxTWl3aWFXRjBJam94TnpRek5EUXdNalV5ZlE="